version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket-management 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./ticket_management.sql:/docker-entrypoint-initdb.d/ticket_management.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork

  server:
    build: ./server/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db 
      DB_USER: root 
      DB_PASSWORD: root
      DB_DATABASE: ticket-management 
    networks:
      - mynetwork

  client:
    build: ./client/
    ports:
      - "8080:8080"
    networks:
      - mynetwork 
    depends_on:
      - server 

networks:
  mynetwork:
    driver: bridge
